In [57]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
fruits=pd.read_csv('fruit-data-with-colours-master/fruit-data-with-colours-master/fruit_data_with_colours.csv')

In [62]:
print(fruits)

    fruit_label fruit_name     fruit_subtype  mass  width  height  color_score
0             1      apple      granny_smith   192    8.4     7.3         0.55
1             1      apple      granny_smith   180    8.0     6.8         0.59
2             1      apple      granny_smith   176    7.4     7.2         0.60
3             2   mandarin          mandarin    86    6.2     4.7         0.80
4             2   mandarin          mandarin    84    6.0     4.6         0.79
5             2   mandarin          mandarin    80    5.8     4.3         0.77
6             2   mandarin          mandarin    80    5.9     4.3         0.81
7             2   mandarin          mandarin    76    5.8     4.0         0.81
8             1      apple          braeburn   178    7.1     7.8         0.92
9             1      apple          braeburn   172    7.4     7.0         0.89
10            1      apple          braeburn   166    6.9     7.3         0.93
11            1      apple          braeburn   172  

In [65]:
x=fruits.iloc[:,4:7].values
print(x)

[[ 8.4   7.3   0.55]
 [ 8.    6.8   0.59]
 [ 7.4   7.2   0.6 ]
 [ 6.2   4.7   0.8 ]
 [ 6.    4.6   0.79]
 [ 5.8   4.3   0.77]
 [ 5.9   4.3   0.81]
 [ 5.8   4.    0.81]
 [ 7.1   7.8   0.92]
 [ 7.4   7.    0.89]
 [ 6.9   7.3   0.93]
 [ 7.1   7.6   0.92]
 [ 7.    7.1   0.88]
 [ 7.3   7.7   0.7 ]
 [ 7.6   7.3   0.69]
 [ 7.7   7.1   0.69]
 [ 7.6   7.5   0.67]
 [ 7.5   7.6   0.73]
 [ 7.5   7.1   0.83]
 [ 7.4   7.2   0.85]
 [ 7.5   7.5   0.86]
 [ 7.4   7.4   0.84]
 [ 7.3   7.1   0.87]
 [ 7.6   7.9   0.88]
 [ 9.    9.4   0.75]
 [ 9.2   9.2   0.75]
 [ 9.6   9.2   0.74]
 [ 7.5   9.2   0.77]
 [ 6.7   7.1   0.72]
 [ 7.    7.4   0.81]
 [ 7.1   7.5   0.79]
 [ 7.8   8.    0.82]
 [ 7.2   7.    0.8 ]
 [ 7.5   8.1   0.74]
 [ 7.6   7.8   0.75]
 [ 7.1   7.9   0.75]
 [ 7.1   7.6   0.76]
 [ 7.3   7.3   0.79]
 [ 7.2   7.8   0.77]
 [ 6.8   7.4   0.75]
 [ 7.1   7.5   0.78]
 [ 7.6   8.2   0.79]
 [ 7.2   7.2   0.82]
 [ 7.2  10.3   0.7 ]
 [ 7.3  10.5   0.72]
 [ 7.2   9.2   0.72]
 [ 7.3  10.2   0.71]
 [ 7.3   9.7 

In [68]:
y=fruits.iloc[:,6].values
print(y)

[0.55 0.59 0.6  0.8  0.79 0.77 0.81 0.81 0.92 0.89 0.93 0.92 0.88 0.7
 0.69 0.69 0.67 0.73 0.83 0.85 0.86 0.84 0.87 0.88 0.75 0.75 0.74 0.77
 0.72 0.81 0.79 0.82 0.8  0.74 0.75 0.75 0.76 0.79 0.77 0.75 0.78 0.79
 0.82 0.7  0.72 0.72 0.71 0.72 0.72 0.73 0.71 0.72 0.72 0.74 0.71 0.72
 0.73 0.72 0.7 ]


In [69]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=100,random_state=0)
regressor.fit(X,y)

RandomForestRegressor(random_state=0)

ValueError: cannot reshape array of size 2 into shape (1,1)