In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
a=np.array((1,2,3))
print(a)

[1 2 3]


In [4]:
import numpy as np
a=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print("Initial Array\n:",a)
sliced_arr=a[:2,::2]
print("Array with first 2 rows and alternate columns(0 and 2):\n",sliced_arr)
Index_arr=a[[1,1,0,3],[3,2,1,0]]
print("Index \n",Index_arr)

Initial Array
: [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]
Index 
 [0. 6. 2. 3.]


In [5]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[4,3],[2,1]])
print("Adding 1 to every elements: ",a+1)
print("\n Subtracting 2 from each elements:",b-2)
print("Sum of All array Elements:",a.sum())
print("Array Sum:\n",a+b)

Adding 1 to every elements:  [[2 3]
 [4 5]]

 Subtracting 2 from each elements: [[ 2  1]
 [ 0 -1]]
Sum of All array Elements: 10
Array Sum:
 [[5 5]
 [5 5]]


In [7]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("Array Type:",type(arr))
print("No of Dimensions:",arr.ndim)
print("Shape Of Array:",arr.shape)
print("Size Of array:",arr.size)
print("type of Element:",arr.dtype)

Array Type: <class 'numpy.ndarray'>
No of Dimensions: 2
Shape Of Array: (2, 3)
Size Of array: 6
type of Element: int32


In [15]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]],dtype='float')
print("Array Created Using List:\n",a)
b=np.array((1,2,3))
print("Array Created Using Tuple\n",b)
#Creating a 3x4 array with all zeros
c=np.zeros((3,4))
print("\n An array initialized with all zeros\n",c)
d=np.full((3,3),6,dtype='complex')
print("\n An array initialized with all 6s:\n",d)
#Create an array with random values
e=np.random.random((2,2))
print("\n A random Array\n",e)
#Create a sequence of integers with 0 to 30 with steps of five
f=np.arange(0,30,5)
print("\n A sequential array with steps of 5:\n",f)
#Create a sequence of 10 values from range 0 to 5
g=np.linspace(0,5,10)
print('\n sequential array iwht 10 values btw 0 and 5\n',g)
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [1,2,0,1]])
newarr=arr.reshape(2,3,2)
print("Original Array:\n",arr)
print("Reshape Array:\n",newarr)
arr=np.array([[1,2,3],[4,5,6]])
flarr=arr.flatten()
print("\n Original Array:\n",arr)
print("Flatten Array:\n",flarr)

Array Created Using List:
 [[1. 2. 4.]
 [5. 8. 7.]]
Array Created Using Tuple
 [1 2 3]

 An array initialized with all zeros
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 An array initialized with all 6s:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

 A random Array
 [[0.34804011 0.62364037]
 [0.10764658 0.80131033]]

 A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

 sequential array iwht 10 values btw 0 and 5
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Original Array:
 [[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
Reshape Array:
 [[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [1 2]
  [0 1]]]

 Original Array:
 [[1 2 3]
 [4 5 6]]
Flatten Array:
 [1 2 3 4 5 6]


In [16]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
#Slicing array
temp=arr[:2,::2]
print(temp)
temp=arr[[0,1,2,3],[3,2,1,0]]
print(temp)
#boolean array indexing example
cond=arr>0
temp=arr[cond]
print("Elements Greater than zero:\n",temp)

[[-1.  0.]
 [ 4.  6.]]
[4. 6. 0. 3.]
Elements Greater than zero:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [17]:
import numpy as np
arr=np.array([[1,5,6],
             [4,7,2],
             [3,1,9]])
print("Largest Element in array:",arr.max())
print("Row Wise max elements:",arr.max(axis=1))
print("Column wise min element:",arr.min(axis=0))
print("Sum of All elements in Array:",arr.sum())
print("Cummulative Sum across each row:",arr.cumsum(axis=1))

Largest Element in array: 9
Row Wise max elements: [6 7 9]
Column wise min element: [1 1 2]
Sum of All elements in Array: 38
Cummulative Sum across each row: [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]
